"""
Django management command to load demo data into the database.
Usage: python manage.py load_demo_data
"""
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from core.models import Category, VideoLesson, Test, Question


class Command(BaseCommand):
    help = 'Load demo data into the database'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Ma\'lumotlar bazasini to\'ldirish boshlandi...'))
        
        # Kategoriyalar yaratish
        self.create_categories()
        
        # Video darslar yaratish
        self.create_videos()
        
        # Testlar yaratish
        self.create_tests()
        
        self.stdout.write(self.style.SUCCESS('\n✅ Barcha ma\'lumotlar muvaffaqiyatli yaratildi!'))

    def create_categories(self):
        """Kategoriyalar yaratish"""
        self.stdout.write('\n📁 Kategoriyalar yaratilmoqda...')
        
        categories_data = [
            {
                'name': 'Reading',
                'slug': 'reading',
                'description': 'IELTS Reading bo\'limi uchun video darslar va testlar',
                'icon': 'fas fa-book-reader',
                'color': '#3b82f6',
                'order': 1,
            },
            {
                'name': 'Writing',
                'slug': 'writing',
                'description': 'IELTS Writing bo\'limi uchun video darslar va testlar',
                'icon': 'fas fa-pen-fancy',
                'color': '#10b981',
                'order': 2,
            },
            {
                'name': 'Listening',
                'slug': 'listening',
                'description': 'IELTS Listening bo\'limi uchun video darslar va testlar',
                'icon': 'fas fa-headphones',
                'color': '#f59e0b',
                'order': 3,
            },
            {
                'name': 'Speaking',
                'slug': 'speaking',
                'description': 'IELTS Speaking bo\'limi uchun video darslar va testlar',
                'icon': 'fas fa-microphone',
                'color': '#ef4444',
                'order': 4,
            },
            {
                'name': 'Grammar',
                'slug': 'grammar',
                'description': 'Grammatika bo\'yicha video darslar va testlar',
                'icon': 'fas fa-language',
                'color': '#8b5cf6',
                'order': 5,
            },
        ]
        
        for cat_data in categories_data:
            category, created = Category.objects.get_or_create(
                slug=cat_data['slug'],
                defaults=cat_data
            )
            if created:
                self.stdout.write(f'  ✅ {category.name} kategoriyasi yaratildi')
            else:
                self.stdout.write(f'  ⚠️  {category.name} kategoriyasi allaqachon mavjud')

    def create_videos(self):
        """Video darslar yaratish"""
        self.stdout.write('\n🎥 Video darslar yaratilmoqda...')
        
        videos_data = [
            # Reading videos
            {
                'title': 'IELTS Reading - True/False/Not Given strategiyasi',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'True/False/Not Given savollarini qanday yechishni o\'rganing. Bu eng qiyin savol turlaridan biri.',
                'order': 1,
            },
            {
                'title': 'IELTS Reading - Matching Headings',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Matching Headings savollarini tez va samarali yechish usullari.',
                'order': 2,
            },
            {
                'title': 'IELTS Reading - Multiple Choice Questions',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Ko\'p tanlovli savollarni yechish strategiyalari va maslahatlar.',
                'order': 3,
            },
            {
                'title': 'IELTS Reading - Summary Completion',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Summary Completion savollarini yechish bo\'yicha to\'liq qo\'llanma.',
                'order': 4,
            },
            {
                'title': 'IELTS Reading - Sentence Completion',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Sentence Completion savollarini tez va to\'g\'ri yechish usullari.',
                'order': 5,
            },
            {
                'title': 'IELTS Reading - Short Answer Questions',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Qisqa javobli savollarni yechish strategiyalari.',
                'order': 6,
            },
            # Writing videos
            {
                'title': 'IELTS Writing Task 1 - Line Graph yozish',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Line Graph yozish bo\'yicha to\'liq qo\'llanma va namuna.',
                'order': 1,
            },
            {
                'title': 'IELTS Writing Task 1 - Bar Chart yozish',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Bar Chart yozish bo\'yicha batafsil tushuntirish.',
                'order': 2,
            },
            {
                'title': 'IELTS Writing Task 1 - Pie Chart yozish',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Pie Chart yozish bo\'yicha professional usullar.',
                'order': 3,
            },
            {
                'title': 'IELTS Writing Task 1 - Table yozish',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Table ma\'lumotlarini tahlil qilish va yozish.',
                'order': 4,
            },
            {
                'title': 'IELTS Writing Task 1 - Process Diagram',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Process Diagram yozish bo\'yicha qo\'llanma.',
                'order': 5,
            },
            {
                'title': 'IELTS Writing Task 2 - Essay yozish',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'IELTS Writing Task 2 uchun professional essay yozish usullari.',
                'order': 6,
            },
            {
                'title': 'IELTS Writing Task 2 - Opinion Essay',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Opinion Essay yozish bo\'yicha batafsil tushuntirish.',
                'order': 7,
            },
            {
                'title': 'IELTS Writing Task 2 - Discussion Essay',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Discussion Essay yozish strategiyalari va namunalar.',
                'order': 8,
            },
            # Listening videos
            {
                'title': 'IELTS Listening - Form Completion',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Form Completion savollarini yechish bo\'yicha maslahatlar.',
                'order': 1,
            },
            {
                'title': 'IELTS Listening - Multiple Choice',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Listening bo\'limidagi ko\'p tanlovli savollarni yechish.',
                'order': 2,
            },
            {
                'title': 'IELTS Listening - Map Labelling',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Map Labelling savollarini yechish strategiyalari.',
                'order': 3,
            },
            {
                'title': 'IELTS Listening - Note Completion',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Note Completion savollarini yechish bo\'yicha qo\'llanma.',
                'order': 4,
            },
            {
                'title': 'IELTS Listening - Sentence Completion',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Sentence Completion savollarini tez yechish usullari.',
                'order': 5,
            },
            {
                'title': 'IELTS Listening - Short Answer Questions',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Qisqa javobli savollarni yechish strategiyalari.',
                'order': 6,
            },
            # Grammar videos
            {
                'title': 'Present Tenses - Hozirgi zamonlar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Present Simple, Present Continuous, Present Perfect va Present Perfect Continuous.',
                'order': 1,
            },
            {
                'title': 'Past Tenses - O\'tgan zamonlar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Past Simple, Past Continuous, Past Perfect va Past Perfect Continuous.',
                'order': 2,
            },
            {
                'title': 'Future Tenses - Kelajak zamonlar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Future Simple, Future Continuous, Future Perfect va Future Perfect Continuous.',
                'order': 3,
            },
            {
                'title': 'Conditional Sentences - Shart gaplar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Zero, First, Second, Third va Mixed Conditionals.',
                'order': 4,
            },
            {
                'title': 'Passive Voice - Passiv ovoz',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Passive Voice qurilishi va ishlatilishi.',
                'order': 5,
            },
            {
                'title': 'Relative Clauses - Nisbiy gap qismlari',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Defining va Non-defining Relative Clauses.',
                'order': 6,
            },
            # Speaking videos
            {
                'title': 'IELTS Speaking Part 1 - Introduction',
                'category_slug': 'speaking',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Speaking Part 1 uchun tayyorgarlik va maslahatlar.',
                'order': 1,
            },
            {
                'title': 'IELTS Speaking Part 2 - Long Turn',
                'category_slug': 'speaking',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Part 2 uchun tayyorgarlik va namuna javoblar.',
                'order': 2,
            },
            {
                'title': 'IELTS Speaking Part 3 - Discussion',
                'category_slug': 'speaking',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Part 3 uchun muhokama qilish strategiyalari.',
                'order': 3,
            },
            # Additional Reading videos
            {
                'title': 'IELTS Reading - Time Management',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Reading testida vaqtni samarali boshqarish strategiyalari.',
                'order': 7,
            },
            {
                'title': 'IELTS Reading - Vocabulary Building',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Reading uchun muhim so\'z boyligini oshirish usullari.',
                'order': 8,
            },
            {
                'title': 'IELTS Reading - Skimming and Scanning',
                'category_slug': 'reading',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Skimming va Scanning texnikalarini o\'rganish.',
                'order': 9,
            },
            # Additional Writing videos
            {
                'title': 'IELTS Writing - Task 1 Overview',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Task 1 ning umumiy ko\'rinishi va asosiy qoidalari.',
                'order': 7,
            },
            {
                'title': 'IELTS Writing - Task 2 Structure',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Task 2 essay uchun to\'g\'ri struktura.',
                'order': 8,
            },
            {
                'title': 'IELTS Writing - Linking Words',
                'category_slug': 'writing',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Linking words va ularning to\'g\'ri ishlatilishi.',
                'order': 9,
            },
            # Additional Listening videos
            {
                'title': 'IELTS Listening - Prediction Techniques',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Javoblarni oldindan taxmin qilish texnikalari.',
                'order': 7,
            },
            {
                'title': 'IELTS Listening - Note-taking Skills',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Samarali eslatma olish ko\'nikmalari.',
                'order': 8,
            },
            {
                'title': 'IELTS Listening - Dealing with Accents',
                'category_slug': 'listening',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Turli xil aksentlarni tushunish strategiyalari.',
                'order': 9,
            },
            # Additional Grammar videos
            {
                'title': 'Modal Verbs - Modallar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Can, could, may, might, must, should va boshqalar.',
                'order': 7,
            },
            {
                'title': 'Articles - Artikllar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'A, an, the artikllarining to\'g\'ri ishlatilishi.',
                'order': 8,
            },
            {
                'title': 'Prepositions - Old qo\'shimchalar',
                'category_slug': 'grammar',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Prepositionlarning IELTS da muhim ishlatilishi.',
                'order': 9,
            },
            # Additional Speaking videos
            {
                'title': 'IELTS Speaking - Fluency Tips',
                'category_slug': 'speaking',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Nutq oqimini yaxshilash maslahatlari.',
                'order': 4,
            },
            {
                'title': 'IELTS Speaking - Pronunciation',
                'category_slug': 'speaking',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'To\'g\'ri talaffuz qilish usullari.',
                'order': 5,
            },
            {
                'title': 'IELTS Speaking - Common Topics',
                'category_slug': 'speaking',
                'youtube_url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'description': 'Eng ko\'p uchraydigan mavzular va ularga tayyorgarlik.',
                'order': 6,
            },
        ]
        
        for video_data in videos_data:
            try:
                category = Category.objects.get(slug=video_data['category_slug'])
                category_slug = video_data.pop('category_slug')
                
                video, created = VideoLesson.objects.get_or_create(
                    title=video_data['title'],
                    category=category,
                    defaults={
                        **video_data,
                        'duration': 600,  # 10 daqiqa
                    }
                )
                if created:
                    self.stdout.write(f'  ✅ {video.title} yaratildi')
                else:
                    self.stdout.write(f'  ⚠️  {video.title} allaqachon mavjud')
            except Category.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'  ⚠️  {video_data["category_slug"]} kategoriyasi topilmadi'))

    def create_tests(self):
        """Testlar va savollar yaratish"""
        self.stdout.write('\n📝 Testlar yaratilmoqda...')
        
        tests_data = [
            # Reading Tests
            {
                'title': 'IELTS Reading Practice Test 1 - Oson',
                'category_slug': 'reading',
                'test_type': 'reading',
                'difficulty': 'easy',
                'description': 'IELTS Reading bo\'yicha oson darajadagi amaliy test. 10 ta savol.',
                'duration_minutes': 20,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What is the main purpose of the passage?',
                        'option_a': 'To describe the history of IELTS',
                        'option_b': 'To explain IELTS test format',
                        'option_c': 'To provide tips for IELTS preparation',
                        'option_d': 'To compare different English tests',
                        'correct_answer': 'c',
                        'explanation': 'The passage focuses on providing tips and strategies for IELTS preparation.',
                        'order': 1,
                    },
                    {
                        'question_text': 'According to the passage, how long does the IELTS test take?',
                        'option_a': '2 hours',
                        'option_b': '2 hours 45 minutes',
                        'option_c': '3 hours',
                        'option_d': '3 hours 30 minutes',
                        'correct_answer': 'b',
                        'explanation': 'The IELTS test takes approximately 2 hours and 45 minutes to complete.',
                        'order': 2,
                    },
                    {
                        'question_text': 'Which section of IELTS is considered the most difficult?',
                        'option_a': 'Reading',
                        'option_b': 'Writing',
                        'option_c': 'Listening',
                        'option_d': 'Speaking',
                        'correct_answer': 'b',
                        'explanation': 'Writing is often considered the most challenging section as it requires strong language skills.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is skimming in reading?',
                        'option_a': 'Reading every word carefully',
                        'option_b': 'Reading quickly to get the main idea',
                        'option_c': 'Reading only the first sentence',
                        'option_d': 'Reading backwards',
                        'correct_answer': 'b',
                        'explanation': 'Skimming is reading quickly to get the general idea or main points of a text.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What is scanning in reading?',
                        'option_a': 'Reading every word',
                        'option_b': 'Looking for specific information',
                        'option_c': 'Reading slowly',
                        'option_d': 'Reading out loud',
                        'correct_answer': 'b',
                        'explanation': 'Scanning is looking for specific information or keywords in a text.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Reading Practice Test 2 - O\'rta',
                'category_slug': 'reading',
                'test_type': 'reading',
                'difficulty': 'medium',
                'description': 'IELTS Reading bo\'yicha o\'rta darajadagi amaliy test. 10 ta savol.',
                'duration_minutes': 20,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'In IELTS Reading, how many passages are there?',
                        'option_a': '2 passages',
                        'option_b': '3 passages',
                        'option_c': '4 passages',
                        'option_d': '5 passages',
                        'correct_answer': 'b',
                        'explanation': 'IELTS Reading test consists of 3 passages with a total of 40 questions.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What is the time limit for IELTS Reading test?',
                        'option_a': '50 minutes',
                        'option_b': '60 minutes',
                        'option_c': '70 minutes',
                        'option_d': '80 minutes',
                        'correct_answer': 'b',
                        'explanation': 'The IELTS Reading test has a time limit of 60 minutes.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What should you do first when reading a passage?',
                        'option_a': 'Read every word carefully',
                        'option_b': 'Read the questions first',
                        'option_c': 'Read the title and headings',
                        'option_d': 'Start answering immediately',
                        'correct_answer': 'c',
                        'explanation': 'It is recommended to first read the title and headings to understand the main topic.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What does "Not Given" mean in True/False/Not Given questions?',
                        'option_a': 'The information is false',
                        'option_b': 'The information is not mentioned',
                        'option_c': 'The information is true',
                        'option_d': 'The information is unclear',
                        'correct_answer': 'b',
                        'explanation': '"Not Given" means the information is not mentioned in the passage at all.',
                        'order': 4,
                    },
                    {
                        'question_text': 'How should you approach Matching Headings questions?',
                        'option_a': 'Read all headings first',
                        'option_b': 'Read the passage first',
                        'option_c': 'Read headings and passage together',
                        'option_d': 'Guess randomly',
                        'correct_answer': 'a',
                        'explanation': 'It is best to read all headings first to understand what to look for in each paragraph.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Reading Practice Test 3 - Qiyin',
                'category_slug': 'reading',
                'test_type': 'reading',
                'difficulty': 'hard',
                'description': 'IELTS Reading bo\'yicha qiyin darajadagi amaliy test. 10 ta savol.',
                'duration_minutes': 20,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'What is the difference between "False" and "Not Given"?',
                        'option_a': 'There is no difference',
                        'option_b': 'False contradicts the passage, Not Given is not mentioned',
                        'option_c': 'False is true, Not Given is false',
                        'option_d': 'Both mean the same thing',
                        'correct_answer': 'b',
                        'explanation': 'False means the statement contradicts information in the passage, while Not Given means the information is not mentioned.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What is the best strategy for time management in Reading?',
                        'option_a': 'Spend equal time on each passage',
                        'option_b': 'Spend more time on difficult passages',
                        'option_c': 'Spend 20 minutes per passage',
                        'option_d': 'Skip difficult questions',
                        'correct_answer': 'c',
                        'explanation': 'The best strategy is to spend approximately 20 minutes on each of the 3 passages.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What should you do if you cannot find an answer?',
                        'option_a': 'Leave it blank',
                        'option_b': 'Guess randomly',
                        'option_c': 'Mark it and come back later',
                        'option_d': 'Skip the entire passage',
                        'correct_answer': 'c',
                        'explanation': 'If you cannot find an answer, mark it and move on, then come back to it later if time permits.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is the key to answering Summary Completion questions?',
                        'option_a': 'Understanding grammar',
                        'option_b': 'Finding synonyms and paraphrasing',
                        'option_c': 'Memorizing vocabulary',
                        'option_d': 'Reading quickly',
                        'correct_answer': 'b',
                        'explanation': 'Summary Completion questions require finding synonyms and understanding paraphrasing in the passage.',
                        'order': 4,
                    },
                    {
                        'question_text': 'How many questions are there in total in IELTS Reading?',
                        'option_a': '30 questions',
                        'option_b': '35 questions',
                        'option_c': '40 questions',
                        'option_d': '45 questions',
                        'correct_answer': 'c',
                        'explanation': 'The IELTS Reading test contains a total of 40 questions across 3 passages.',
                        'order': 5,
                    },
                ],
            },
            # Writing Tests
            {
                'title': 'IELTS Writing Practice Test 1 - Oson',
                'category_slug': 'writing',
                'test_type': 'writing',
                'difficulty': 'easy',
                'description': 'IELTS Writing bo\'yicha oson darajadagi amaliy test. 5 ta savol.',
                'duration_minutes': 15,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What is the recommended word count for IELTS Writing Task 1?',
                        'option_a': 'At least 100 words',
                        'option_b': 'At least 150 words',
                        'option_c': 'At least 200 words',
                        'option_d': 'At least 250 words',
                        'correct_answer': 'b',
                        'explanation': 'Task 1 requires at least 150 words, while Task 2 requires at least 250 words.',
                        'order': 1,
                    },
                    {
                        'question_text': 'How many paragraphs should an IELTS Task 2 essay have?',
                        'option_a': '2 paragraphs',
                        'option_b': '3 paragraphs',
                        'option_c': '4 paragraphs',
                        'option_d': '5 paragraphs',
                        'correct_answer': 'd',
                        'explanation': 'A well-structured Task 2 essay should have 5 paragraphs: introduction, 3 body paragraphs, and conclusion.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What should you do in the introduction of Task 1?',
                        'option_a': 'Give your opinion',
                        'option_b': 'Paraphrase the question',
                        'option_c': 'List all data',
                        'option_d': 'Write a conclusion',
                        'correct_answer': 'b',
                        'explanation': 'In Task 1, the introduction should paraphrase the question to show understanding.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is the minimum word count for IELTS Writing Task 2?',
                        'option_a': '200 words',
                        'option_b': '250 words',
                        'option_c': '300 words',
                        'option_d': '350 words',
                        'correct_answer': 'b',
                        'explanation': 'Task 2 requires at least 250 words. Writing less will result in a lower score.',
                        'order': 4,
                    },
                    {
                        'question_text': 'How much time should you spend on Task 1?',
                        'option_a': '10 minutes',
                        'option_b': '15 minutes',
                        'option_c': '20 minutes',
                        'option_d': '30 minutes',
                        'correct_answer': 'c',
                        'explanation': 'You should spend about 20 minutes on Task 1 and 40 minutes on Task 2.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Writing Practice Test 2 - O\'rta',
                'category_slug': 'writing',
                'test_type': 'writing',
                'difficulty': 'medium',
                'description': 'IELTS Writing bo\'yicha o\'rta darajadagi amaliy test. 5 ta savol.',
                'duration_minutes': 15,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What should Task 1 overview contain?',
                        'option_a': 'Detailed data',
                        'option_b': 'Main trends and key features',
                        'option_c': 'Personal opinions',
                        'option_d': 'Future predictions',
                        'correct_answer': 'b',
                        'explanation': 'The overview should summarize the main trends and key features of the data.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What is the structure of a Task 2 essay?',
                        'option_a': 'Introduction, Body, Conclusion',
                        'option_b': 'Introduction, 2 Body paragraphs, Conclusion',
                        'option_c': 'Introduction, 3 Body paragraphs, Conclusion',
                        'option_d': 'Introduction, 4 Body paragraphs, Conclusion',
                        'correct_answer': 'c',
                        'explanation': 'A well-structured Task 2 essay has: Introduction, 3 Body paragraphs, and Conclusion.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What should you avoid in Task 1?',
                        'option_a': 'Using data',
                        'option_b': 'Giving opinions or predictions',
                        'option_c': 'Describing trends',
                        'option_d': 'Using numbers',
                        'correct_answer': 'b',
                        'explanation': 'In Task 1, you should only describe what you see, not give opinions or make predictions.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is the purpose of the conclusion in Task 2?',
                        'option_a': 'Introduce new ideas',
                        'option_b': 'Summarize main points and restate opinion',
                        'option_c': 'Provide more examples',
                        'option_d': 'Ask questions',
                        'correct_answer': 'b',
                        'explanation': 'The conclusion should summarize the main points and restate your opinion clearly.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What vocabulary should you use in Task 1?',
                        'option_a': 'Simple words only',
                        'option_b': 'Academic and descriptive vocabulary',
                        'option_c': 'Informal language',
                        'option_d': 'Slang words',
                        'correct_answer': 'b',
                        'explanation': 'Task 1 requires academic and descriptive vocabulary to describe data accurately.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Writing Practice Test 3 - Qiyin',
                'category_slug': 'writing',
                'test_type': 'writing',
                'difficulty': 'hard',
                'description': 'IELTS Writing bo\'yicha qiyin darajadagi amaliy test. 5 ta savol.',
                'duration_minutes': 15,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'What is the difference between Task 1 and Task 2?',
                        'option_a': 'Task 1 is longer',
                        'option_b': 'Task 1 is descriptive, Task 2 is argumentative',
                        'option_c': 'Task 2 is easier',
                        'option_d': 'There is no difference',
                        'correct_answer': 'b',
                        'explanation': 'Task 1 requires describing data, while Task 2 requires presenting an argument or opinion.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What is coherence in writing?',
                        'option_a': 'Using big words',
                        'option_b': 'Logical organization and flow of ideas',
                        'option_c': 'Writing quickly',
                        'option_d': 'Using many examples',
                        'correct_answer': 'b',
                        'explanation': 'Coherence refers to the logical organization and smooth flow of ideas in your writing.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is cohesion in writing?',
                        'option_a': 'Using linking words',
                        'option_b': 'Connecting ideas with appropriate devices',
                        'option_c': 'Writing long sentences',
                        'option_d': 'Using complex grammar',
                        'correct_answer': 'b',
                        'explanation': 'Cohesion means connecting ideas using appropriate linking words, pronouns, and other devices.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What should you do if you exceed the word count?',
                        'option_a': 'Delete random words',
                        'option_b': 'Continue writing',
                        'option_c': 'It is fine, no penalty',
                        'option_d': 'Check for unnecessary words',
                        'correct_answer': 'c',
                        'explanation': 'There is no penalty for exceeding the word count, but you should manage your time effectively.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What is lexical resource in IELTS Writing?',
                        'option_a': 'Using simple words',
                        'option_b': 'Using a wide range of vocabulary appropriately',
                        'option_c': 'Using only complex words',
                        'option_d': 'Avoiding synonyms',
                        'correct_answer': 'b',
                        'explanation': 'Lexical resource refers to using a wide range of vocabulary appropriately and accurately.',
                        'order': 5,
                    },
                ],
            },
            # Listening Tests
            {
                'title': 'IELTS Listening Practice Test 1 - Oson',
                'category_slug': 'listening',
                'test_type': 'listening',
                'difficulty': 'easy',
                'description': 'IELTS Listening bo\'yicha oson darajadagi amaliy test. 8 ta savol.',
                'duration_minutes': 30,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What should you do before the recording starts?',
                        'option_a': 'Read the questions quickly',
                        'option_b': 'Listen carefully',
                        'option_c': 'Write down notes',
                        'option_d': 'All of the above',
                        'correct_answer': 'd',
                        'explanation': 'Before the recording starts, you should read questions, listen carefully, and be ready to take notes.',
                        'order': 1,
                    },
                    {
                        'question_text': 'How many times do you hear each recording in IELTS Listening?',
                        'option_a': 'Once',
                        'option_b': 'Twice',
                        'option_c': 'Three times',
                        'option_d': 'As many times as you want',
                        'correct_answer': 'a',
                        'explanation': 'In IELTS Listening, each recording is played only once, so you must listen carefully.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is the total time for IELTS Listening test?',
                        'option_a': '30 minutes',
                        'option_b': '40 minutes',
                        'option_c': '50 minutes',
                        'option_d': '60 minutes',
                        'correct_answer': 'a',
                        'explanation': 'The IELTS Listening test takes 30 minutes, including the time to transfer answers.',
                        'order': 3,
                    },
                    {
                        'question_text': 'How many sections are there in IELTS Listening?',
                        'option_a': '2 sections',
                        'option_b': '3 sections',
                        'option_c': '4 sections',
                        'option_d': '5 sections',
                        'correct_answer': 'c',
                        'explanation': 'IELTS Listening test consists of 4 sections with 10 questions each.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What should you do if you miss an answer?',
                        'option_a': 'Panic',
                        'option_b': 'Leave it blank and move on',
                        'option_c': 'Stop listening',
                        'option_d': 'Ask to replay',
                        'correct_answer': 'b',
                        'explanation': 'If you miss an answer, leave it blank and move on to the next question to avoid missing more.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Listening Practice Test 2 - O\'rta',
                'category_slug': 'listening',
                'test_type': 'listening',
                'difficulty': 'medium',
                'description': 'IELTS Listening bo\'yicha o\'rta darajadagi amaliy test. 8 ta savol.',
                'duration_minutes': 30,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What type of information is usually tested in Section 1?',
                        'option_a': 'Academic lectures',
                        'option_b': 'Everyday social situations',
                        'option_c': 'Complex discussions',
                        'option_d': 'Scientific topics',
                        'correct_answer': 'b',
                        'explanation': 'Section 1 typically involves everyday social situations like booking a hotel or ordering food.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What should you pay attention to in Map Labelling questions?',
                        'option_a': 'Colors',
                        'option_b': 'Directions and landmarks',
                        'option_c': 'People\'s names',
                        'option_d': 'Numbers only',
                        'correct_answer': 'b',
                        'explanation': 'In Map Labelling, you need to pay attention to directions (left, right, north, south) and landmarks.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is the difficulty level progression in Listening?',
                        'option_a': 'Easy to hard',
                        'option_b': 'Hard to easy',
                        'option_c': 'All sections are equal',
                        'option_d': 'Random difficulty',
                        'correct_answer': 'a',
                        'explanation': 'The Listening test progresses from easier (Section 1) to more difficult (Section 4).',
                        'order': 3,
                    },
                    {
                        'question_text': 'How should you write numbers in Listening?',
                        'option_a': 'Only in words',
                        'option_b': 'Only in digits',
                        'option_c': 'Either words or digits',
                        'option_d': 'In Roman numerals',
                        'correct_answer': 'c',
                        'explanation': 'You can write numbers either in words or digits, both are acceptable.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What should you do during the 10-minute transfer time?',
                        'option_a': 'Relax',
                        'option_b': 'Transfer answers carefully to answer sheet',
                        'option_c': 'Check spelling',
                        'option_d': 'All of the above',
                        'correct_answer': 'd',
                        'explanation': 'Use the transfer time to carefully transfer answers, check spelling, and ensure accuracy.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Listening Practice Test 3 - Qiyin',
                'category_slug': 'listening',
                'test_type': 'listening',
                'difficulty': 'hard',
                'description': 'IELTS Listening bo\'yicha qiyin darajadagi amaliy test. 8 ta savol.',
                'duration_minutes': 30,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'What is the main challenge in Section 4?',
                        'option_a': 'Fast speech',
                        'option_b': 'Academic vocabulary and complex ideas',
                        'option_c': 'Multiple speakers',
                        'option_d': 'Background noise',
                        'correct_answer': 'b',
                        'explanation': 'Section 4 is challenging because it contains academic vocabulary and complex ideas from lectures.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What should you listen for in Multiple Choice questions?',
                        'option_a': 'Exact words from options',
                        'option_b': 'Synonyms and paraphrasing',
                        'option_c': 'Only the first option',
                        'option_d': 'The longest option',
                        'correct_answer': 'b',
                        'explanation': 'In Multiple Choice, the correct answer is often expressed using synonyms and paraphrasing, not exact words.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is the key to answering Note Completion questions?',
                        'option_a': 'Writing everything you hear',
                        'option_b': 'Following the structure and predicting answers',
                        'option_c': 'Ignoring the structure',
                        'option_d': 'Guessing randomly',
                        'correct_answer': 'b',
                        'explanation': 'Note Completion requires following the structure of the notes and predicting what type of answer is needed.',
                        'order': 3,
                    },
                    {
                        'question_text': 'How many questions are there in total in IELTS Listening?',
                        'option_a': '30 questions',
                        'option_b': '35 questions',
                        'option_c': '40 questions',
                        'option_d': '45 questions',
                        'correct_answer': 'c',
                        'explanation': 'The IELTS Listening test contains 40 questions across 4 sections.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What should you do if speakers correct themselves?',
                        'option_a': 'Ignore the correction',
                        'option_b': 'Listen to the corrected information',
                        'option_c': 'Write both versions',
                        'option_d': 'Stop listening',
                        'correct_answer': 'b',
                        'explanation': 'If speakers correct themselves, the corrected information is usually the right answer.',
                        'order': 5,
                    },
                ],
            },
            # Additional Reading Tests
            {
                'title': 'IELTS Reading Practice Test 4 - Vocabulary',
                'category_slug': 'reading',
                'test_type': 'reading',
                'difficulty': 'medium',
                'description': 'IELTS Reading bo\'yicha vocabulary test. 8 ta savol.',
                'duration_minutes': 20,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What does "infer" mean in reading context?',
                        'option_a': 'To state directly',
                        'option_b': 'To understand indirectly',
                        'option_c': 'To ignore',
                        'option_d': 'To summarize',
                        'correct_answer': 'b',
                        'explanation': 'To infer means to understand or conclude something indirectly from evidence and reasoning.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What is a synonym?',
                        'option_a': 'A word with opposite meaning',
                        'option_b': 'A word with similar meaning',
                        'option_c': 'A word with no meaning',
                        'option_d': 'A made-up word',
                        'correct_answer': 'b',
                        'explanation': 'A synonym is a word that has the same or similar meaning as another word.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is an antonym?',
                        'option_a': 'A word with similar meaning',
                        'option_b': 'A word with opposite meaning',
                        'option_c': 'A word with no meaning',
                        'option_d': 'A technical term',
                        'correct_answer': 'b',
                        'explanation': 'An antonym is a word that has the opposite meaning of another word.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What does "paraphrase" mean?',
                        'option_a': 'To copy exactly',
                        'option_b': 'To express in different words',
                        'option_c': 'To translate',
                        'option_d': 'To summarize briefly',
                        'correct_answer': 'b',
                        'explanation': 'To paraphrase means to express the same meaning using different words.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What is the main idea of a passage?',
                        'option_a': 'A supporting detail',
                        'option_b': 'The central point or message',
                        'option_c': 'A random fact',
                        'option_d': 'The conclusion only',
                        'correct_answer': 'b',
                        'explanation': 'The main idea is the central point or primary message that the author wants to convey.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Reading Practice Test 5 - Advanced',
                'category_slug': 'reading',
                'test_type': 'reading',
                'difficulty': 'hard',
                'description': 'IELTS Reading bo\'yicha ilg\'or test. 10 ta savol.',
                'duration_minutes': 20,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'What is the purpose of topic sentences?',
                        'option_a': 'To confuse readers',
                        'option_b': 'To introduce the main idea of a paragraph',
                        'option_c': 'To provide examples',
                        'option_d': 'To conclude the paragraph',
                        'correct_answer': 'b',
                        'explanation': 'Topic sentences introduce the main idea of a paragraph and help readers understand the paragraph\'s focus.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What should you do when you encounter an unknown word?',
                        'option_a': 'Skip the entire passage',
                        'option_b': 'Use context clues to understand',
                        'option_c': 'Look it up immediately',
                        'option_d': 'Ignore it completely',
                        'correct_answer': 'b',
                        'explanation': 'You should use context clues (surrounding words and sentences) to understand the meaning of unknown words.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is the difference between fact and opinion?',
                        'option_a': 'There is no difference',
                        'option_b': 'Facts are provable, opinions are beliefs',
                        'option_c': 'Facts are always wrong',
                        'option_d': 'Opinions are always true',
                        'correct_answer': 'b',
                        'explanation': 'Facts are statements that can be proven true or false, while opinions are personal beliefs or judgments.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is the best way to improve reading speed?',
                        'option_a': 'Skip all words',
                        'option_b': 'Practice regularly with various texts',
                        'option_c': 'Read only easy texts',
                        'option_d': 'Avoid reading altogether',
                        'correct_answer': 'b',
                        'explanation': 'Regular practice with various types of texts is the best way to improve reading speed and comprehension.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What should you focus on in the first reading?',
                        'option_a': 'Every single word',
                        'option_b': 'Main ideas and overall structure',
                        'option_c': 'Only the conclusion',
                        'option_d': 'Random details',
                        'correct_answer': 'b',
                        'explanation': 'In the first reading, focus on understanding the main ideas and overall structure of the text.',
                        'order': 5,
                    },
                ],
            },
            # Additional Writing Tests
            {
                'title': 'IELTS Writing Practice Test 4 - Task 1 Types',
                'category_slug': 'writing',
                'test_type': 'writing',
                'difficulty': 'medium',
                'description': 'IELTS Writing Task 1 bo\'yicha turli xil diagram turlari. 6 ta savol.',
                'duration_minutes': 15,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What should you include in a Line Graph description?',
                        'option_a': 'Only numbers',
                        'option_b': 'Trends, comparisons, and key features',
                        'option_c': 'Personal opinions',
                        'option_d': 'Future predictions',
                        'correct_answer': 'b',
                        'explanation': 'A Line Graph description should include trends (increases, decreases), comparisons between lines, and key features.',
                        'order': 1,
                    },
                    {
                        'question_text': 'How should you organize a Bar Chart description?',
                        'option_a': 'Randomly',
                        'option_b': 'By categories or highest to lowest values',
                        'option_c': 'Alphabetically',
                        'option_d': 'By color',
                        'correct_answer': 'b',
                        'explanation': 'Organize a Bar Chart description logically, either by categories or by ordering values from highest to lowest.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is important in a Pie Chart description?',
                        'option_a': 'Listing all percentages',
                        'option_b': 'Highlighting largest and smallest segments, making comparisons',
                        'option_c': 'Describing colors only',
                        'option_d': 'Ignoring percentages',
                        'correct_answer': 'b',
                        'explanation': 'In a Pie Chart, highlight the largest and smallest segments and make meaningful comparisons between segments.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What should you do in a Process Diagram?',
                        'option_a': 'Describe steps in order',
                        'option_b': 'Skip steps randomly',
                        'option_c': 'Only describe the first step',
                        'option_d': 'Describe only the last step',
                        'correct_answer': 'a',
                        'explanation': 'In a Process Diagram, describe all steps in chronological order from start to finish.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What vocabulary is useful for describing trends?',
                        'option_a': 'Only "increase" and "decrease"',
                        'option_b': 'Variety of verbs, nouns, and adverbs (rise, fall, sharply, gradually)',
                        'option_c': 'Only numbers',
                        'option_d': 'Slang words',
                        'correct_answer': 'b',
                        'explanation': 'Use a variety of vocabulary including verbs (rise, fall), nouns (increase, decrease), and adverbs (sharply, gradually) to describe trends.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Writing Practice Test 5 - Task 2 Advanced',
                'category_slug': 'writing',
                'test_type': 'writing',
                'difficulty': 'hard',
                'description': 'IELTS Writing Task 2 bo\'yicha ilg\'or test. 6 ta savol.',
                'duration_minutes': 15,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'What is the structure of a good argument?',
                        'option_a': 'Random ideas',
                        'option_b': 'Claim, evidence, reasoning',
                        'option_c': 'Only opinions',
                        'option_d': 'No structure needed',
                        'correct_answer': 'b',
                        'explanation': 'A good argument has a clear structure: claim (your position), evidence (supporting facts), and reasoning (explanation).',
                        'order': 1,
                    },
                    {
                        'question_text': 'What should you avoid in academic writing?',
                        'option_a': 'Formal language',
                        'option_b': 'Contractions, slang, and personal pronouns',
                        'option_c': 'Complex sentences',
                        'option_d': 'Examples',
                        'correct_answer': 'b',
                        'explanation': 'Avoid contractions (don\'t, can\'t), slang, and excessive use of personal pronouns (I, you) in academic writing.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What makes a strong topic sentence?',
                        'option_a': 'Vague statements',
                        'option_b': 'Clear, specific, and arguable statement',
                        'option_c': 'Questions only',
                        'option_d': 'Random words',
                        'correct_answer': 'b',
                        'explanation': 'A strong topic sentence is clear, specific, and presents an arguable point that the paragraph will support.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is the purpose of examples in an essay?',
                        'option_a': 'To fill space',
                        'option_b': 'To support and illustrate your main points',
                        'option_c': 'To confuse readers',
                        'option_d': 'To avoid explaining',
                        'correct_answer': 'b',
                        'explanation': 'Examples are used to support and illustrate your main points, making your argument more convincing.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What should the conclusion do?',
                        'option_a': 'Introduce new ideas',
                        'option_b': 'Summarize main points and reinforce your position',
                        'option_c': 'Ask new questions',
                        'option_d': 'Repeat the introduction word for word',
                        'correct_answer': 'b',
                        'explanation': 'The conclusion should summarize the main points discussed and reinforce your position without introducing new ideas.',
                        'order': 5,
                    },
                ],
            },
            # Additional Listening Tests
            {
                'title': 'IELTS Listening Practice Test 4 - Strategies',
                'category_slug': 'listening',
                'test_type': 'listening',
                'difficulty': 'medium',
                'description': 'IELTS Listening bo\'yicha strategiyalar testi. 7 ta savol.',
                'duration_minutes': 30,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What should you do during the 30-second pause?',
                        'option_a': 'Relax completely',
                        'option_b': 'Read the next set of questions',
                        'option_c': 'Stop listening',
                        'option_d': 'Write random notes',
                        'correct_answer': 'b',
                        'explanation': 'During the 30-second pause, use the time to read the next set of questions to prepare.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What is the best way to handle distractors?',
                        'option_a': 'Believe everything you hear',
                        'option_b': 'Listen for information that is corrected or changed',
                        'option_c': 'Ignore corrections',
                        'option_d': 'Write down everything',
                        'correct_answer': 'b',
                        'explanation': 'Distractors are incorrect options mentioned in the recording. Listen for information that is corrected or changed.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What should you do if speakers have accents?',
                        'option_a': 'Panic',
                        'option_b': 'Focus on key words and context',
                        'option_c': 'Stop listening',
                        'option_d': 'Complain',
                        'correct_answer': 'b',
                        'explanation': 'If speakers have accents, focus on key words and context rather than getting distracted by pronunciation.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What is important in Sentence Completion?',
                        'option_a': 'Writing long sentences',
                        'option_b': 'Following word limit and grammar rules',
                        'option_c': 'Ignoring instructions',
                        'option_d': 'Writing anything',
                        'correct_answer': 'b',
                        'explanation': 'In Sentence Completion, follow the word limit (usually NO MORE THAN TWO WORDS) and ensure your answer fits grammatically.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What should you do if you cannot spell a word?',
                        'option_a': 'Leave it blank',
                        'option_b': 'Write it phonetically and check later',
                        'option_c': 'Skip the question',
                        'option_d': 'Guess randomly',
                        'correct_answer': 'b',
                        'explanation': 'If you cannot spell a word, write it phonetically during the test and check spelling during the transfer time.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Listening Practice Test 5 - Advanced',
                'category_slug': 'listening',
                'test_type': 'listening',
                'difficulty': 'hard',
                'description': 'IELTS Listening bo\'yicha ilg\'or test. 8 ta savol.',
                'duration_minutes': 30,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'What is the key to understanding academic lectures?',
                        'option_a': 'Memorizing everything',
                        'option_b': 'Understanding structure and key concepts',
                        'option_c': 'Ignoring structure',
                        'option_d': 'Only listening to numbers',
                        'correct_answer': 'b',
                        'explanation': 'Understanding the structure (introduction, main points, examples, conclusion) and key concepts is crucial for academic lectures.',
                        'order': 1,
                    },
                    {
                        'question_text': 'What should you listen for in discussions?',
                        'option_a': 'Only one speaker',
                        'option_b': 'Different viewpoints and agreements/disagreements',
                        'option_c': 'Background music',
                        'option_d': 'Only questions',
                        'correct_answer': 'b',
                        'explanation': 'In discussions, listen for different viewpoints, agreements, disagreements, and how speakers respond to each other.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What is the best strategy for Multiple Choice with 3 options?',
                        'option_a': 'Guess randomly',
                        'option_b': 'Eliminate wrong options and listen for the correct one',
                        'option_c': 'Choose the first option',
                        'option_d': 'Choose the longest option',
                        'correct_answer': 'b',
                        'explanation': 'The best strategy is to eliminate obviously wrong options and listen carefully for the correct answer.',
                        'order': 3,
                    },
                    {
                        'question_text': 'What should you do if the answer is not mentioned?',
                        'option_a': 'Make something up',
                        'option_b': 'Leave it blank or write "Not Given"',
                        'option_c': 'Copy from another question',
                        'option_d': 'Write random words',
                        'correct_answer': 'b',
                        'explanation': 'If the answer is not mentioned in the recording, leave it blank or mark it as "Not Given" rather than guessing.',
                        'order': 4,
                    },
                    {
                        'question_text': 'What is the importance of prediction in Listening?',
                        'option_a': 'No importance',
                        'option_b': 'Helps you focus on what to listen for',
                        'option_c': 'Wastes time',
                        'option_d': 'Confuses you',
                        'correct_answer': 'b',
                        'explanation': 'Prediction helps you anticipate what type of information you need to listen for, making it easier to identify answers.',
                        'order': 5,
                    },
                ],
            },
            # Grammar Tests
            {
                'title': 'IELTS Grammar Practice Test 1 - Tenses',
                'category_slug': 'grammar',
                'test_type': 'reading',
                'difficulty': 'easy',
                'description': 'Zamonlar bo\'yicha grammatika testi. 6 ta savol.',
                'duration_minutes': 10,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'Choose the correct sentence:',
                        'option_a': 'She go to school every day.',
                        'option_b': 'She goes to school every day.',
                        'option_c': 'She going to school every day.',
                        'option_d': 'She went to school every day.',
                        'correct_answer': 'b',
                        'explanation': 'For third-person singular (she, he, it) in Present Simple, add -es to the verb.',
                        'order': 1,
                    },
                    {
                        'question_text': 'Which sentence uses the Present Perfect tense correctly?',
                        'option_a': 'I have seen him yesterday.',
                        'option_b': 'I saw him yesterday.',
                        'option_c': 'I have seen him many times.',
                        'option_d': 'I am seeing him now.',
                        'correct_answer': 'c',
                        'explanation': 'Present Perfect is used for actions that started in the past and continue to the present, or for past actions with present relevance.',
                        'order': 2,
                    },
                    {
                        'question_text': 'Identify the passive voice sentence:',
                        'option_a': 'The student wrote the essay.',
                        'option_b': 'The essay was written by the student.',
                        'option_c': 'The student is writing the essay.',
                        'option_d': 'The student will write the essay.',
                        'correct_answer': 'b',
                        'explanation': 'Passive voice uses "to be" verb + past participle (was written) and the agent (by the student) is optional.',
                        'order': 3,
                    },
                    {
                        'question_text': 'Complete the sentence: If I had known, I ______ you.',
                        'option_a': 'would tell',
                        'option_b': 'would have told',
                        'option_c': 'will tell',
                        'option_d': 'had told',
                        'correct_answer': 'b',
                        'explanation': 'This is a Third Conditional sentence (If + Past Perfect, would have + Past Participle).',
                        'order': 4,
                    },
                    {
                        'question_text': 'Which relative pronoun is used for people?',
                        'option_a': 'Which',
                        'option_b': 'Whose',
                        'option_c': 'Where',
                        'option_d': 'Who',
                        'correct_answer': 'd',
                        'explanation': '"Who" is used to refer to people, while "which" is for things, "where" for places, and "whose" for possession.',
                        'order': 5,
                    },
                ],
            },
            {
                'title': 'IELTS Grammar Practice Test 2 - Advanced',
                'category_slug': 'grammar',
                'test_type': 'reading',
                'difficulty': 'medium',
                'description': 'Ilg\'or grammatika testi. 6 ta savol.',
                'duration_minutes': 10,
                'passing_score': 70,
                'questions': [
                    {
                        'question_text': 'Choose the sentence with the correct use of articles:',
                        'option_a': 'He is a honest man.',
                        'option_b': 'He is an honest man.',
                        'option_c': 'He is honest man.',
                        'option_d': 'He is the honest man.',
                        'correct_answer': 'b',
                        'explanation': 'Use "an" before words that start with a vowel sound, even if the letter is a consonant (e.g., honest).',
                        'order': 1,
                    },
                    {
                        'question_text': 'Which modal verb expresses strong obligation?',
                        'option_a': 'Can',
                        'option_b': 'May',
                        'option_c': 'Must',
                        'option_d': 'Should',
                        'correct_answer': 'c',
                        'explanation': '"Must" indicates a strong obligation or necessity.',
                        'order': 2,
                    },
                    {
                        'question_text': 'Correct the error: "Despite of the rain, we went for a walk."',
                        'option_a': 'Despite the rain,',
                        'option_b': 'In spite the rain,',
                        'option_c': 'Although the rain,',
                        'option_d': 'However the rain,',
                        'correct_answer': 'a',
                        'explanation': '"Despite" is followed directly by a noun or gerund, without "of". "In spite of" uses "of".',
                        'order': 3,
                    },
                    {
                        'question_text': 'Which sentence uses a gerund correctly?',
                        'option_a': 'I enjoy to read books.',
                        'option_b': 'I enjoy reading books.',
                        'option_c': 'I enjoy read books.',
                        'option_d': 'I enjoy have read books.',
                        'correct_answer': 'b',
                        'explanation': 'The verb "enjoy" is typically followed by a gerund (verb + -ing).',
                        'order': 4,
                    },
                    {
                        'question_text': 'Identify the sentence with a dangling participle:',
                        'option_a': 'Running quickly, he caught the bus.',
                        'option_b': 'Having finished the work, the bell rang.',
                        'option_c': 'Written in haste, the letter contained many errors.',
                        'option_d': 'Walking home, I saw a cat.',
                        'correct_answer': 'b',
                        'explanation': 'A dangling participle occurs when the subject of the participle (Having finished) is not the same as the subject of the main clause (the bell).',
                        'order': 5,
                    },
                ],
            },
            # Speaking Tests
            {
                'title': 'IELTS Speaking Practice Test 1 - Introduction',
                'category_slug': 'speaking',
                'test_type': 'speaking',
                'difficulty': 'easy',
                'description': 'IELTS Speaking Part 1 bo\'yicha test. 4 ta savol.',
                'duration_minutes': 5,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'What is your full name?',
                        'option_a': 'My name is John.',
                        'option_b': 'My full name is John Smith.',
                        'option_c': 'John Smith.',
                        'option_d': 'I am John.',
                        'correct_answer': 'b',
                        'explanation': 'It\'s important to provide your full name as requested in the introduction.',
                        'order': 1,
                    },
                    {
                        'question_text': 'Do you work or study?',
                        'option_a': 'Yes, I do.',
                        'option_b': 'I work as a software engineer.',
                        'option_c': 'I study.',
                        'option_d': 'I am a student.',
                        'correct_answer': 'b',
                        'explanation': 'Provide a detailed answer, not just a yes/no. Mention your profession or field of study.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What do you like about your job/studies?',
                        'option_a': 'It is good.',
                        'option_b': 'I like it very much.',
                        'option_c': 'I enjoy the problem-solving aspect of my job and learning new technologies.',
                        'option_d': 'It is interesting.',
                        'correct_answer': 'c',
                        'explanation': 'Elaborate on your answer with specific details and examples to demonstrate your fluency and vocabulary.',
                        'order': 3,
                    },
                    {
                        'question_text': 'Where are you from?',
                        'option_a': 'I am from Tashkent.',
                        'option_b': 'I come from Tashkent, which is the capital city of Uzbekistan.',
                        'option_c': 'Tashkent.',
                        'option_d': 'From Tashkent.',
                        'correct_answer': 'b',
                        'explanation': 'Provide a complete answer with additional information to show your language ability.',
                        'order': 4,
                    },
                ],
            },
            {
                'title': 'IELTS Speaking Practice Test 2 - Long Turn',
                'category_slug': 'speaking',
                'test_type': 'speaking',
                'difficulty': 'medium',
                'description': 'IELTS Speaking Part 2 bo\'yicha test. 4 ta savol.',
                'duration_minutes': 7,
                'passing_score': 60,
                'questions': [
                    {
                        'question_text': 'Describe a place you would like to visit in the future.',
                        'option_a': 'I want to go to Paris.',
                        'option_b': 'I would like to visit Paris because it is beautiful.',
                        'option_c': 'I dream of visiting Kyoto, Japan. Its ancient temples, serene gardens, and vibrant culture deeply fascinate me. I\'d love to experience the traditional tea ceremonies and explore its historic districts.',
                        'option_d': 'Paris is a good place.',
                        'correct_answer': 'c',
                        'explanation': 'For Part 2, provide a detailed and well-structured response, including reasons and examples.',
                        'order': 1,
                    },
                    {
                        'question_text': 'How important is it to travel to different countries?',
                        'option_a': 'It is very important.',
                        'option_b': 'It is not important.',
                        'option_c': 'Traveling to different countries is immensely important as it broadens one\'s perspective, fosters cultural understanding, and offers invaluable life experiences. It exposes individuals to diverse ways of life, challenging preconceived notions and promoting personal growth.',
                        'option_d': 'Some people like it.',
                        'correct_answer': 'c',
                        'explanation': 'For Part 3, provide a well-reasoned and extended answer, discussing broader issues and offering justifications.',
                        'order': 2,
                    },
                    {
                        'question_text': 'What are the benefits of learning a new language?',
                        'option_a': 'It is good for your brain.',
                        'option_b': 'It helps you communicate.',
                        'option_c': 'Learning a new language offers numerous cognitive benefits, such as improved memory and problem-solving skills. Furthermore, it enhances communication abilities, opens doors to new cultures, and can significantly boost career opportunities in a globalized world.',
                        'option_d': 'You can talk to foreigners.',
                        'correct_answer': 'c',
                        'explanation': 'Provide a comprehensive answer with multiple benefits and explanations.',
                        'order': 3,
                    },
                    {
                        'question_text': 'How can technology help language learning?',
                        'option_a': 'It is useful.',
                        'option_b': 'Technology helps a lot.',
                        'option_c': 'Technology revolutionizes language learning by providing interactive apps, online courses, and virtual reality experiences. It enables personalized learning, instant feedback, and access to native speakers worldwide, making language acquisition more engaging and effective than traditional methods.',
                        'option_d': 'We can use apps.',
                        'correct_answer': 'c',
                        'explanation': 'Provide a detailed answer with specific examples and explanations.',
                        'order': 4,
                    },
                ],
            },
        ]
        
        for test_data in tests_data:
            try:
                category = Category.objects.get(slug=test_data['category_slug'])
                questions_data = test_data.pop('questions')
                category_slug = test_data.pop('category_slug')
                
                # Check if test already exists
                test = Test.objects.filter(
                    title=test_data['title'],
                    category=category
                ).first()
                
                if not test:
                    # Add category to test_data
                    test_data['category'] = category
                    test = Test.objects.create(**test_data)
                    created = True
                else:
                    created = False
                
                if created:
                    self.stdout.write(f'  ✅ {test.title} yaratildi')
                    
                    # Savollar yaratish
                    for q_data in questions_data:
                        Question.objects.create(
                            test=test,
                            **q_data
                        )
                    self.stdout.write(f'     → {len(questions_data)} ta savol qo\'shildi')
                else:
                    self.stdout.write(f'  ⚠️  {test.title} allaqachon mavjud')
            except Category.DoesNotExist:
                self.stdout.write(self.style.WARNING(f'  ⚠️  {test_data["category_slug"]} kategoriyasi topilmadi'))

