# Generated by Django 4.2.16 on 2026-02-07 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (Font Awesome)')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Rang (hex)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Playlist Video',
                'verbose_name_plural': 'Playlist Videolar',
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm')),
                ('audio_timestamp', models.FloatField(blank=True, null=True, verbose_name='Audio vaqti (soniya) - Listening')),
                ('option_a', models.CharField(max_length=500, verbose_name='Variant A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Variant B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Variant C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Variant D')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('points', models.IntegerField(default=1, verbose_name='Ball')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('test_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening')], max_length=20, verbose_name='Test turi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik darajasi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('passing_score', models.IntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('allow_retake', models.BooleanField(default=True, verbose_name='Qayta ishlashga ruxsat')),
                ('max_attempts', models.IntegerField(blank=True, null=True, verbose_name="Maksimal urinishlar soni (bo'sh bo'lsa cheksiz)")),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='test_audio/', verbose_name='Audio fayl (Listening)')),
                ('reading_text', models.TextField(blank=True, verbose_name="O'qish matni (Reading)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('youtube_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='YouTube ID')),
                ('youtube_thumbnail', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration', models.IntegerField(default=0, verbose_name='Davomiyligi (soniya)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Video Dars',
                'verbose_name_plural': 'Video Darslar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Reyting (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.videolesson', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video Reyting',
                'verbose_name_plural': 'Video Reytinglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Playlist nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_public', models.BooleanField(default=False, verbose_name='Ochiq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('videos', models.ManyToManyField(related_name='playlists', through='core.PlaylistVideo', to='core.videolesson', verbose_name='Videolar')),
            ],
            options={
                'verbose_name': 'Video Playlist',
                'verbose_name_plural': 'Video Playlistlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Eslatma matni')),
                ('timestamp', models.IntegerField(default=0, verbose_name='Vaqt (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_notes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.videolesson', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video Eslatma',
                'verbose_name_plural': 'Video Eslatmalar',
                'ordering': ['timestamp', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Izoh matni')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Tahrirlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.videocomment', verbose_name='Javob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.videolesson', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video Izoh',
                'verbose_name_plural': 'Video Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False, verbose_name="Ko'rilgan")),
                ('watch_percentage', models.IntegerField(default=0, verbose_name='Foiz (0-100)')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name="Oxirgi ko'rilgan vaqt")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.videolesson', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video Progress',
                'verbose_name_plural': 'Video Progresslar',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Jami savollar')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('correct_answers', models.IntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('wrong_answers', models.IntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('time_taken', models.IntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('answers_json', models.JSONField(default=dict, verbose_name='Javoblar (JSON)')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Urinish raqami')),
                ('is_paused', models.BooleanField(default=False, verbose_name="To'xtatilgan")),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan vaqt")),
                ('paused_duration', models.IntegerField(default=0, verbose_name="To'xtatilgan vaqt (soniya)")),
                ('timer_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Timer boshlangan vaqt')),
                ('timer_seconds_left', models.IntegerField(blank=True, null=True, verbose_name='Timer qolgan vaqt (soniya)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Foydalanuvchi javobi')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Savol')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.usertestresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'Test Javobi',
                'verbose_name_plural': 'Test Javoblari',
                'ordering': ['test_result', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Kirish'), ('test_start', 'Test boshlash'), ('test_complete', 'Test yakunlash'), ('video_watch', "Video ko'rish")], max_length=20, verbose_name='Faollik turi')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name="Bog'liq obyekt ID")),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name="Bog'liq obyekt turi")),
                ('metadata', models.JSONField(default=dict, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Faollik',
                'verbose_name_plural': 'Faolliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('activities_count', models.IntegerField(default=0, verbose_name='Faolliklar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Study Streak',
                'verbose_name_plural': 'Study Streaks',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='core.videoplaylist', verbose_name='Playlist'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='core.videolesson', verbose_name='Video'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='core_catego_slug_cc5975_idx'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.test', verbose_name='Test'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.videolesson', verbose_name='Video'),
        ),
        migrations.AddIndex(
            model_name='videorating',
            index=models.Index(fields=['user', 'video'], name='core_videor_user_id_387de6_idx'),
        ),
        migrations.AddIndex(
            model_name='videorating',
            index=models.Index(fields=['video', 'rating'], name='core_videor_video_i_5e1f69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videorating',
            unique_together={('user', 'video')},
        ),
        migrations.AddIndex(
            model_name='videoplaylist',
            index=models.Index(fields=['user', '-created_at'], name='core_videop_user_id_f130a5_idx'),
        ),
        migrations.AddIndex(
            model_name='videoplaylist',
            index=models.Index(fields=['is_public'], name='core_videop_is_publ_8f41eb_idx'),
        ),
        migrations.AddIndex(
            model_name='videonote',
            index=models.Index(fields=['user', 'video'], name='core_videon_user_id_727c59_idx'),
        ),
        migrations.AddIndex(
            model_name='videonote',
            index=models.Index(fields=['video', 'timestamp'], name='core_videon_video_i_cb383a_idx'),
        ),
        migrations.AddIndex(
            model_name='videolesson',
            index=models.Index(fields=['category', 'is_active'], name='core_videol_categor_f9b7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='videolesson',
            index=models.Index(fields=['youtube_id'], name='core_videol_youtube_f11776_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['video', '-created_at'], name='core_videoc_video_i_de8a66_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['user', '-created_at'], name='core_videoc_user_id_c842c6_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['parent'], name='core_videoc_parent__6c889f_idx'),
        ),
        migrations.AddIndex(
            model_name='uservideoprogress',
            index=models.Index(fields=['user', 'video'], name='core_uservi_user_id_788f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='uservideoprogress',
            index=models.Index(fields=['user', 'watched'], name='core_uservi_user_id_5d6691_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together={('user', 'video')},
        ),
        migrations.AddIndex(
            model_name='usertestresult',
            index=models.Index(fields=['user', 'test'], name='core_userte_user_id_01345b_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestresult',
            index=models.Index(fields=['user', '-completed_at'], name='core_userte_user_id_f34936_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestanswer',
            index=models.Index(fields=['test_result', 'question'], name='core_userte_test_re_668684_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', '-created_at'], name='core_userac_user_id_858224_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='core_userac_created_140080_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['category', 'test_type', 'is_active'], name='core_test_categor_596372_idx'),
        ),
        migrations.AddIndex(
            model_name='studystreak',
            index=models.Index(fields=['user', '-date'], name='core_studys_user_id_9d07fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studystreak',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'order'], name='core_questi_test_id_71a1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistvideo',
            index=models.Index(fields=['playlist', 'order'], name='core_playli_playlis_f49f53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together={('playlist', 'video')},
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'video'], name='core_bookma_user_id_6a3d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'test'], name='core_bookma_user_id_cc7889_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'video'), ('user', 'test')},
        ),
    ]
