# Generated by Django 4.2.16 on 2026-02-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_question_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice (A/B/C/D)'), ('true_false', 'True / False'), ('true_false_not_given', 'True / False / Not Given (Reading)'), ('yes_no_not_given', 'Yes / No / Not Given'), ('fill_blank', "Bo'sh joyni to'ldirish (bitta so'z)"), ('summary_completion', 'Summary Completion (Reading)'), ('notes_completion', 'Notes Completion (Listening)'), ('sentence_completion', 'Sentence Completion'), ('table_completion', 'Table Completion'), ('short_answer', 'Qisqa javob'), ('matching_headings', 'Matching Headings (matnga sarlavha)'), ('matching_sentences', 'Matching Sentence Endings'), ('matching_features', 'Matching Features (elementlarni toifalarga)'), ('matching_info', 'Matching Information (paragraflarga)'), ('classification', 'Classification (A/B/C ga tasniflash)'), ('list_selection', "List Selection (ro'yxatdan tanlash)")], default='mcq', max_length=30, verbose_name='Savol turi'),
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Set nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Flashcard Set',
                'verbose_name_plural': 'Flashcard Setlar',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('definition', models.TextField(blank=True, verbose_name='Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.flashcardset', verbose_name='Set')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='core.question', verbose_name='Manba savol')),
                ('source_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='core.test', verbose_name='Manba test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcardlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['user', 'name'], name='core_flashc_user_id_a36b5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardset',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', '-created_at'], name='core_flashc_user_id_8781e3_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set'], name='core_flashc_flashca_7aad61_idx'),
        ),
    ]
