# Generated by Django 4.2.16 on 2026-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sat_extra_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='core_catego_parent__68b602_idx',
            old_name='core_catego_parent__5a5c44_idx',
        ),
        migrations.RenameIndex(
            model_name='satresource',
            new_name='core_satres_subject_4b6b7a_idx',
            old_name='core_satres_subject_0f2ccd_idx',
        ),
        migrations.RenameIndex(
            model_name='satresourcebookmark',
            new_name='core_satres_user_id_b0c0cd_idx',
            old_name='core_satreso_user_id_644620_idx',
        ),
        migrations.RenameIndex(
            model_name='satresourcenote',
            new_name='core_satres_user_id_66517c_idx',
            old_name='core_satreso_user_id_6f8a63_idx',
        ),
        migrations.RenameIndex(
            model_name='satresourceprogress',
            new_name='core_satres_user_id_9d5d62_idx',
            old_name='core_satreso_user_id_2f4f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='satresourceprogress',
            new_name='core_satres_user_id_0dc1a6_idx',
            old_name='core_satreso_user_id_b4922b_idx',
        ),
        migrations.AlterField(
            model_name='question',
            name='options_json',
            field=models.JSONField(blank=True, default=dict, help_text='MCQ: {"mcq_single_slot": true}, variantlar {"options": [...]}. To\'ldirish: {"instruction": "NO MORE THAN TWO WORDS"} yoki {"max_words_per_blank": 2}.', verbose_name="Qo'shimcha parametrlar (JSON)"),
        ),
        migrations.AlterField(
            model_name='questiontyperule',
            name='shart_text',
            field=models.TextField(blank=True, help_text="Faqat admin uchun yordam matni (masalan: [1],[2] va vergul bilan javoblar). Savol qo'shish formasida va JS da ko'rinadi; test yechayotgan foydalanuvchiga chiqmaydi.", verbose_name='Shart (qoida / talab)'),
        ),
    ]
