# Generated by Django 4.2.16 on 2026-04-15 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_user_module_access(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserModuleAccess = apps.get_model('core', 'UserModuleAccess')
    for user in User.objects.all().iterator():
        UserModuleAccess.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_question_max_choices_three'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_ielts', models.BooleanField(default=True, verbose_name="IELTS bo'limiga ruxsat")),
                ('can_access_sat', models.BooleanField(default=True, verbose_name="SAT bo'limiga ruxsat")),
                ('can_access_jobs', models.BooleanField(default=False, verbose_name="Jobs bo'limiga ruxsat")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'User Module Access',
                'verbose_name_plural': 'User Module Accesslar',
            },
        ),
        migrations.RunPython(seed_user_module_access, migrations.RunPython.noop),
    ]
