# Generated by Django 4.2.16 on 2026-04-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usermoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleaccess',
            name='active_session_key',
            field=models.CharField(blank=True, help_text='Bir foydalanuvchi bir vaqtda faqat bitta session bilan kirishi uchun ishlatiladi.', max_length=64, null=True, verbose_name='Aktiv session kaliti'),
        ),
    ]
