# Generated by Django 4.2.16 on 2026-04-26 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_usermoduleaccess_active_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='satresourcebookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='satresourcebookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('general', 'Umumiy'), ('video', 'Video'), ('pdf', 'PDF')], default='general', max_length=10, verbose_name='Bookmark turi'),
        ),
        migrations.AlterUniqueTogether(
            name='satresourcebookmark',
            unique_together={('user', 'resource', 'bookmark_type')},
        ),
        migrations.AddIndex(
            model_name='satresourcebookmark',
            index=models.Index(fields=['user', 'bookmark_type'], name='core_satres_user_id_678d96_idx'),
        ),
    ]
