# Generated by Django 4.2.16 on 2026-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_satresourcebookmark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satresourceprogress',
            name='last_position_seconds',
            field=models.IntegerField(default=0, verbose_name='Oxirgi pozitsiya (soniya)'),
        ),
    ]
