# Generated by Django 4.2.16 on 2026-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_satresourceprogress_last_position_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('link_url', models.URLField(blank=True, verbose_name='Havola (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Admin E'loni",
                'verbose_name_plural': "Admin E'lonlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='core_admina_is_acti_ff9ab2_idx')],
            },
        ),
    ]
