# Generated by Django 4.2.7 on 2026-07-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_adminannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWritingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('provider_name', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('estimated_band', models.FloatField(blank=True, null=True, verbose_name='Taxminiy band')),
                ('task_achievement', models.FloatField(blank=True, null=True, verbose_name='Task Achievement')),
                ('coherence_cohesion', models.FloatField(blank=True, null=True, verbose_name='Coherence & Cohesion')),
                ('lexical_resource', models.FloatField(blank=True, null=True, verbose_name='Lexical Resource')),
                ('grammar_range_accuracy', models.FloatField(blank=True, null=True, verbose_name='Grammar Range & Accuracy')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='Kuchli tomonlar')),
                ('improvements', models.JSONField(blank=True, default=list, verbose_name='Yaxshilash kerak')),
                ('next_steps', models.JSONField(blank=True, default=list, verbose_name='Keyingi qadamlar')),
                ('rewrite_suggestion', models.TextField(blank=True, verbose_name='Yaxshiroq yondashuv')),
                ('summary', models.TextField(blank=True, verbose_name='Qisqa xulosa')),
                ('raw_response_json', models.JSONField(blank=True, default=dict, verbose_name='Raw response')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_writing_feedback', to='core.question', verbose_name='Savol')),
                ('test_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='core.usertestanswer', verbose_name='Essay javobi')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_writing_feedback', to='core.usertestresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'AI Writing Feedback',
                'verbose_name_plural': 'AI Writing Feedback',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['test_result', 'status'], name='core_aiwrit_test_re_4f6f02_idx'), models.Index(fields=['question', 'status'], name='core_aiwrit_questio_9d55e6_idx')],
            },
        ),
    ]
