# Generated by Django 4.2.7 on 2026-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_aiwritingfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwritingfeedback',
            name='vocabulary_upgrades',
            field=models.JSONField(blank=True, default=list, help_text="[{from, to, why}] — oddiy so'z → ball oshiradigan variant", verbose_name="So'z almashtirishlar"),
        ),
    ]
