# Generated by Django 4.2.7 on 2026-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_aiwritingfeedback_vocabulary_upgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwritingfeedback',
            name='sentence_corrections',
            field=models.JSONField(blank=True, default=list, help_text='[{original, corrected, type, why}] — essaydan olingan aniq tuzatish', verbose_name='Gap/frazani tuzatishlar'),
        ),
    ]
