# Generated by Django 4.2.7 on 2026-08-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_aiwritingfeedback_writing_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiwritingfeedback',
            name='writing_errors',
            field=models.JSONField(blank=True, default=list, help_text='[{wrong, correct, type, why}] — grammatika, imlo va boshqa aniq xatolar', verbose_name='Aniq xatolar'),
        ),
        migrations.CreateModel(
            name='AIAnswerExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(max_length=80, verbose_name='Slot kaliti')),
                ('display_num', models.PositiveIntegerField(default=0, verbose_name="Ko'rsatish raqami")),
                ('user_part', models.CharField(blank=True, max_length=500, verbose_name='Foydalanuvchi javobi')),
                ('correct_part', models.CharField(blank=True, max_length=500, verbose_name="To'g'ri javob")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('provider_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('why_wrong', models.TextField(blank=True, verbose_name='Nega xato')),
                ('tip', models.TextField(blank=True, verbose_name='Maslahat')),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_answer_explanations', to='core.question', verbose_name='Savol')),
                ('test_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanations', to='core.usertestanswer', verbose_name='Javob')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_answer_explanations', to='core.usertestresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'AI Answer Explanation',
                'verbose_name_plural': 'AI Answer Explanations',
                'ordering': ['display_num', 'id'],
                'indexes': [models.Index(fields=['test_result', 'status'], name='core_aiansw_test_re_57a7cd_idx')],
                'unique_together': {('test_result', 'slot_key')},
            },
        ),
    ]
