# Generated by Django 4.2.7 on 2026-08-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ai_answer_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianswerexplanation',
            name='evidence_quote',
            field=models.CharField(blank=True, max_length=400, verbose_name='Dalil iqtibos'),
        ),
        migrations.AddField(
            model_name='aianswerexplanation',
            name='trap',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tuzoq / distractor'),
        ),
        migrations.CreateModel(
            name='AITestInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True, verbose_name='Umumiy xulosa')),
                ('weak_types', models.JSONField(blank=True, default=list, verbose_name='Zaif savol turlari')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='Kuchli tomonlar')),
                ('next_steps', models.JSONField(blank=True, default=list, verbose_name='Keyingi qadamlar')),
                ('focus_tip', models.TextField(blank=True, verbose_name='Asosiy maslahat')),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_test_insight', to='core.usertestresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'AI Test Insight',
                'verbose_name_plural': 'AI Test Insights',
            },
        ),
    ]
