# Generated by Django 4.2.7 on 2026-08-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rl_ai_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='ai_language',
            field=models.CharField(default='uz', help_text="uz = o'zbekcha, ru = ruscha", max_length=8, verbose_name='AI tili'),
        ),
    ]
