# Generated by Django 4.2.16 on 2026-02-07 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Kod',
                'verbose_name_plural': 'OTP Kodlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['otp_code', 'is_used'], name='accounts_us_otp_cod_e4da12_idx'), models.Index(fields=['user', 'is_used'], name='accounts_us_user_id_e04f47_idx')],
            },
        ),
    ]
